# Bagian Awal

<center> Bagian Pertama </center>
<b> Ini Bold </b>
<i> Italic </i>

<h1> Bagian Awal </h1>

ini adalah contoh fungsi matematika: $$\frac{1}{5}$$

ini adalah contoh fungsi <b> matematika <b>: $\frac{1}{5}$

# Operasi Matematika

In [4]:
# penjumlahan matematika
1+1

2

In [5]:
# pengurangan
3-1

1

In [6]:
# pembagian
5 / 3

1.6666666666666667

In [7]:
# pembagian mengahsilkan bilangan bulat
5 // 3

1

In [8]:
# perkalian
4 * 5

20

In [9]:
# pangkat
2 ** 3

8

In [10]:
# modulo = sisa
7 % 2

1

In [11]:
# gabugan
7 + 5 * 3 - 2 

20

In [12]:
# pembagian dan perkalian
4 * 3 / 2

6.0

# Tipe Data

In [13]:
# String 
"Saya belajar hari minggu"

'Saya belajar hari minggu'

In [14]:
# String 2
'Saya belajar hari minggu'

'Saya belajar hari minggu'

In [19]:
a = 1
b = 2
c = 3

In [20]:
a = 2
b = 1
c = 4

In [21]:
a

2

## List

In [22]:
['a', 'b', 'c', 'd', 3, 6, 7, 8]

['a', 'b', 'c', 'd', 3, 6, 7, 8]

In [23]:
list1 = ['a', 'b', 'c', 'd', 3, 6, 7, 8]

In [24]:
list1

['a', 'b', 'c', 'd', 3, 6, 7, 8]

In [25]:
list1[2] #manggil dari kanan mulai dari nol

'c'

In [26]:
list1[1:4] #yg dibelakang ditambah 1

['b', 'c', 'd']

In [27]:
list1[1:4] + list1 [0:2] #tambahin isi list1 yg diinginkan

['b', 'c', 'd', 'a', 'b']

In [29]:
list1[1:4] + list1[6:7]

['b', 'c', 'd', 7]

In [32]:
list1.append('1') #tambah atau menyisipkan elemen

In [33]:
list1

['a', 'b', 'c', 'd', 3, 6, 7, 8, 'a', '1']

In [36]:
del list1[-1] #menghapus satu argumen

In [37]:
list1

['a', 'b', 'c', 'd', 3, 6, 7, 8]

In [38]:
list2 = [1,2,3,4,'a', 'b', [5,6,7], ['c', 'd', 'e'], [[1,2,3], ['bc', 'de', 'ef']]] 

In [39]:
list2

[1,
 2,
 3,
 4,
 'a',
 'b',
 [5, 6, 7],
 ['c', 'd', 'e'],
 [[1, 2, 3], ['bc', 'de', 'ef']]]

In [40]:
list2[7] #mengeluarkan/memanggil

['c', 'd', 'e']

In [41]:
list2[7][1] #memanggil dibagian tsb

'd'

In [42]:
list2[-1][0][1]

2

In [43]:
d=300

In [44]:
list2.insert(1,d) #menambahkan dibagian yg diinginkan

In [45]:
list2

[1,
 300,
 2,
 3,
 4,
 'a',
 'b',
 [5, 6, 7],
 ['c', 'd', 'e'],
 [[1, 2, 3], ['bc', 'de', 'ef']]]

# Tuple

In [46]:
(1,2,3,4)

(1, 2, 3, 4)

In [47]:
(1,2,3,4,'a', 'b', 'c')

(1, 2, 3, 4, 'a', 'b', 'c')

In [50]:
(1,2,3,4) + (1,2,3,4)

(1, 2, 3, 4, 1, 2, 3, 4)

In [51]:
tuple1= (1,2,3,4)

In [52]:
tuple1

(1, 2, 3, 4)

In [53]:
list(tuple1) #mengubah tuple ke list

[1, 2, 3, 4]

In [54]:
tuple(list1)

('a', 'b', 'c', 'd', 3, 6, 7, 8)

## Sets (Himpunan)

In [55]:
{1,2,3,4,5, 'a', 'b', 'c'}

{1, 2, 3, 4, 5, 'a', 'b', 'c'}

In [57]:
set1 = {1,2,3,4,5}
set2 = {4,5,6,7,8}

In [58]:
set1.union(set2) #ga duplikat kalo ada data yg sama

{1, 2, 3, 4, 5, 6, 7, 8}

In [59]:
set1.intersection(set2) #kalo mau liat data yg sama

{4, 5}

In [60]:
set1 - set2 #pengurangan himpunan

{1, 2, 3}

In [61]:
set2 - set1

{6, 7, 8}

In [62]:
#gabisa manggil langsung angkanya, harus diubah ke list dulu

In [63]:
list(set1)

[1, 2, 3, 4, 5]

In [64]:
list(set1)[3]

4

In [65]:
set(list1)

{3, 6, 7, 8, 'a', 'b', 'c', 'd'}

## Dictionary

In [67]:
{'nama':['Aditya', 'Toni', 'Tono', 'Ani']}

{'nama': ['Aditya', 'Toni', 'Tono', 'Ani']}

In [69]:
{'nama':['Aditya', 'Toni', 'Tono', 'Ani'], 'tinggi badan': [150, 155, 160,167]}

{'nama': ['Aditya', 'Toni', 'Tono', 'Ani'],
 'tinggi badan': [150, 155, 160, 167]}

In [133]:
dicti1 = {'nama':['Aditya', 'Toni', 'Tono', 'Ani'], 'tinggi badan': [150, 155, 160,167]}

In [77]:
dicti1

{'nama': ['Aditya', 'Toni', 'Tono', 'Ani'],
 'tinggi badan': [150, 155, 160, 167]}

In [79]:
#ingin manggil
dicti1['nama']

['Aditya', 'Toni', 'Tono', 'Ani']

In [80]:
#nambah key
dicti1['berat badan'] = [50, 55, 60, 65]

In [84]:
dicti1

{'nama': ['Aditya', 'Toni', 'Tono', 'Ani'],
 'tinggi badan': [150, 155, 160, 167],
 'berat badan': [50, 55, 60, 65]}

In [88]:
#menghapus
dicti1.pop('tinggi badan')

In [89]:
dicti1

{'nama': ['Aditya', 'Toni', 'Tono', 'Ani'], 'berat badan': [50, 55, 60, 65]}

In [90]:
dicti2 =  {'nama':['Aditya', 'Toni', 'Tono', 'Ani'], 'tinggi badan': [150, 155, 160,]}

In [91]:
dicti2

{'nama': ['Aditya', 'Toni', 'Tono', 'Ani'], 'tinggi badan': [150, 155, 160]}

In [94]:
dicti2['nama'] = ['Toni', 'Tono', 'Ani', 'Ana']

In [95]:
dicti2

{'nama': ['Toni', 'Tono', 'Ani', 'Ana'], 'tinggi badan': [150, 155, 160]}

In [96]:
dicti2['nama'][1] = 'Aditya'

In [97]:
dicti2

{'nama': ['Toni', 'Aditya', 'Ani', 'Ana'], 'tinggi badan': [150, 155, 160]}

# Conditional Statement (If - Else)

In [98]:
nilai = 81

if nilai > 80:
    print('Nilai > 80')
else:
    print('Nilai < 80')

Nilai > 80


In [99]:
nilai = 81
if nilai > 80:
    print('Nilai > 80')
else:
    print('Nilai < 80')

Nilai > 80


In [100]:
nilai 80

if nilai > 80:
    print('A (Nilai > 80)')
elif nilai > 70:
    print('B (nilai 71 - 80)')
else:
    print('C (nilai <= 70)')

SyntaxError: invalid syntax (1281614601.py, line 1)

In [101]:
nilai = 84


# Looping

In [102]:
#for loop
#range(1,5) -> [1,2,3,4]

for i in range (1,5):
    print(i)

1
2
3
4


In [103]:
list1 = ['Aditya', 'Tono', 'Tini', 'Ani']

for nama in list1:
    print(nama)

Aditya
Tono
Tini
Ani


In [104]:
# while 
# i nya harus di update, kalau ga jalan terus

i = 0
while i < 5:
    print(i)
    i = i+1

0
1
2
3
4


In [105]:
for i in range(1,20):
    if i % 2 == 0:
        print(i,'genap')
    else:
        print(i,'ganjil')

1 ganjil
2 genap
3 ganjil
4 genap
5 ganjil
6 genap
7 ganjil
8 genap
9 ganjil
10 genap
11 ganjil
12 genap
13 ganjil
14 genap
15 ganjil
16 genap
17 ganjil
18 genap
19 ganjil


 # Function

#def func_name(a,b):

def penjumlahan(a + b):
    print(a + b)

In [110]:
def penjumlahan(a,b):
    hsl = a + b
    return hsl
hasil = penjumlahan(3,4)

In [111]:
hasil

7

# Package vs Module

In [147]:
import math as m

# Array

In [115]:
import numpy as np

In [116]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [118]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [119]:
array1 + 3

array([4, 5, 6, 7, 8])

In [120]:
array1 * 3

array([ 3,  6,  9, 12, 15])

In [122]:
mat1 = np.array([[1,2,3],[2,3,4]])
mat1

array([[1, 2, 3],
       [2, 3, 4]])

In [123]:
mat1.T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [124]:
mat1 @ mat1.T

array([[14, 20],
       [20, 29]])

In [126]:
mat2 = np.array([[1,2,],[2,1]])
mat2

array([[1, 2],
       [2, 1]])

In [128]:
mat3 = np.array([[3,4,],[4,3]])
mat3

array([[3, 4],
       [4, 3]])

In [129]:
mat2 * mat3

array([[3, 8],
       [8, 3]])

In [130]:
mat2 @ mat3

array([[11, 10],
       [10, 11]])

In [131]:
np.linalg.inv(mat2)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

# DataFrame

In [132]:
import pandas as pd

In [135]:
dicti1 = {'nama':['Aditya', 'Toni', 'Tono', 'Ani'], 'tinggi badan': [150, 155, 160,167]}
dicti1

{'nama': ['Aditya', 'Toni', 'Tono', 'Ani'],
 'tinggi badan': [150, 155, 160, 167]}

In [136]:
pd.DataFrame(dicti1)

nama  tinggi badan
0  Aditya           150
1    Toni           155
2    Tono           160
3     Ani           167

In [137]:
df = pd.DataFrame(dicti1)

In [138]:
df['nama']

0    Aditya
1      Toni
2      Tono
3       Ani
Name: nama, dtype: object

In [146]:
df['berat badan'] = [55, 56, 57, 58]
df

nama  tinggi badan  berat badan
0  Aditya           150           55
1    Toni           155           56
2    Tono           160           57
3     Ani           167           58